# Importing Libraries

In [ ]:
import numpy as np 
import pandas as pd 

from sklearn.metrics import make_scorer,mean_squared_error
from sklearn.model_selection import train_test_split,cross_validate
from sklearn import preprocessing


import xgboost as xgb 

import scipy.stats as stats
import gc


from subprocess import check_output




#Used for data analysis and manipulation
import numpy as np
import pandas as pd

#Used for data visualization
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#Used for preprocessing the data or scaling the data 
from sklearn import preprocessing 
from sklearn.preprocessing import RobustScaler,MinMaxScaler


#Used for splitting the data for cross-validation and validation
from sklearn import model_selection
from sklearn.model_selection import train_test_split,StratifiedKFold,KFold,StratifiedShuffleSplit

#For GridSearch CV
from sklearn.model_selection import GridSearchCV

#Used for different regression and classifier models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,ExtraTreesClassifier,GradientBoostingClassifier
#from catboost import CatBoostRegressor,CatBoostClassifier
import xgboost as xgb
import lightgbm as lgb

#Used for model performance calculation
from sklearn.metrics import confusion_matrix, roc_auc_score ,roc_curve,auc

#Used for garbage collecting
import gc

#For ignoring unneccessary warnings
import warnings
warnings.filterwarnings('ignore')

#For files and folders related operations 
#import os

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
!pwd

/content/data_folder

# Reading the data set

In [ ]:
traindf=pd.read_csv("train.csv")
testdf=pd.read_csv("test.csv")

In [ ]:
traindf.head()

   ID  var3  var15  ...  saldo_medio_var44_ult3          var38  TARGET
0   1     2     23  ...                     0.0   39205.170000       0
1   3     2     34  ...                     0.0   49278.030000       0
2   4     2     23  ...                     0.0   67333.770000       0
3   8     2     37  ...                     0.0   64007.970000       0
4  10     2     39  ...                     0.0  117310.979016       0

[5 rows x 371 columns]

# Let's check if the data set is balanced or not

In [ ]:
traindf["TARGET"].value_counts()/traindf.shape[0]

0    0.960431
1    0.039569
Name: TARGET, dtype: float64

# Concatenating train and test data set for cleaning purpose

In [ ]:
testdf["TARGET"]=1
traindf["Data_ID"]="train"
testdf["Data_ID"]="test"

In [ ]:
df=pd.concat([traindf,testdf],axis=0,ignore_index=True)

In [ ]:
df.head()

   ID  var3  var15  ...  saldo_medio_var44_ult3          var38  TARGET
0   1     2     23  ...                     0.0   39205.170000       0
1   3     2     34  ...                     0.0   49278.030000       0
2   4     2     23  ...                     0.0   67333.770000       0
3   8     2     37  ...                     0.0   64007.970000       0
4  10     2     39  ...                     0.0  117310.979016       0

[5 rows x 371 columns]

# Checking Column types

In [ ]:
df.dtypes.value_counts()

int64      256
float64    115
object       1
dtype: int64

Index(['Data_ID'], dtype='object')

# Checking Percentage of Missing Values

In [ ]:
(df.isnull().sum()/df.shape[0]).sort_values(ascending=False).head(5)

Data_ID              0.0
num_op_var41_ult1    0.0
num_var26            0.0
num_var25_0          0.0
num_var25            0.0
dtype: float64

# Imputing Missing Values

In [ ]:
for x in df.columns:
  if x not in ["ID","Data_ID","target"]:
    if df[x].dtype=="O":
      df[x],_=pd.factorize(df[x])
    else :
      df[x].fillna(df[x].mean(),inplace=True)

# Splitting back into train and test data set

In [ ]:
traindf=df[df.Data_ID=="train"]
testdf=df[df.Data_ID=="test"]

In [ ]:
traindf.drop("Data_ID",axis=1,inplace=True)
testdf.drop("Data_ID",axis=1,inplace=True)

In [ ]:
traindf.head()

   ID  var3  var15  ...  saldo_medio_var44_ult3          var38  TARGET
0   1     2     23  ...                     0.0   39205.170000       0
1   3     2     34  ...                     0.0   49278.030000       0
2   4     2     23  ...                     0.0   67333.770000       0
3   8     2     37  ...                     0.0   64007.970000       0
4  10     2     39  ...                     0.0  117310.979016       0

[5 rows x 371 columns]

# Splitting train data into two parts ,one for training and other for validation

In [ ]:


X = traindf.drop(["TARGET","ID"], axis=1)
Y = traindf['TARGET']

In [ ]:
testIDs=testdf.ID
testdf.drop(["TARGET","ID"],axis=1,inplace=True)

In [ ]:
Y.value_counts()

0    73012
1     3008
Name: TARGET, dtype: int64

In [ ]:
3008/73012

0.04119870706185284

In [ ]:
train_X, val_X, train_Y, val_Y = train_test_split(X, Y, test_size = 0.15, random_state = 123)

# Model Without Validation

In [ ]:
model = DecisionTreeClassifier(max_depth=6,min_samples_split=20)
model.fit(train_X,train_Y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=20,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
roc_auc_score(train_Y,model.predict(train_X))

0.5085685078751326

In [ ]:
score_val = roc_auc_score(val_Y,model.predict(val_X))
print("The auc for validation dataset {: 0.2f}".format(score_val))

The auc for validation dataset  0.50

# Types of Cross-Validation

In [ ]:

#kfold = KFold(n_splits=4, shuffle=True,random_state=123)

#Shuffles and split once .Split is such that the ratio of labels in target column remains same in each fold 
kfold=StratifiedKFold(n_splits=4,shuffle=True,random_state=123)

#Shuffles and split 4 times or 5 times depending on n_splits parameter
#kfold=StratifiedShuffleSplit(n_splits=4,random_state=123)

# Modelling with train and validation split with kfolds

In [ ]:

for i,(train_index,val_index) in enumerate(kfold.split(X,Y)):
    train_X,val_X = X.loc[train_index],X.loc[val_index]
    train_Y,val_Y = Y.loc[train_index],Y.loc[val_index]
    
    print('Score for fold number {} '.format(i),":")
    
    #model
    model= DecisionTreeClassifier(max_depth=2,min_samples_split=5,max_leaf_nodes=5)
    model.fit(train_X,train_Y)
        
    score_val = roc_auc_score(val_Y,model.predict(val_X))
    score_train = roc_auc_score(train_Y,model.predict(train_X))
    
    print('ROC for train data  {:0.2f}'.format(score_train),'   ROC for Validation data {:0.2f}'.format(score_val),"\n")

Score for fold number 0  :
ROC for train data  0.50    ROC for Validation data 0.50

Score for fold number 1  :
ROC for train data  0.50    ROC for Validation data 0.50

Score for fold number 2  :
ROC for train data  0.50    ROC for Validation data 0.50

Score for fold number 3  :
ROC for train data  0.50    ROC for Validation data 0.50

# Xgboosst CV

In [ ]:
params = { 
   "objective": "binary:logistic",
   "booster": "gbtree",
   "eval_metric": "auc",
   "eta": 0.1, 
   "min_child_weight": 100,
   "subsample": 0.75,
   "colsample_bytree": 0.68,
   "max_depth": 6,
   "lambda":0.2
}

d_train = xgb.DMatrix(train_X, train_Y)

cv_results= xgb.cv(params, d_train, num_boost_round=500, nfold=4, seed=123, stratified=False,
                     early_stopping_rounds=25, verbose_eval=100, show_stdv=True)

num_boost_rounds = len(cv_results)

print(num_boost_rounds)

[0]	train-auc:0.826592+0.00144707	test-auc:0.815712+0.00107338
[100]	train-auc:0.850981+0.000911676	test-auc:0.836159+0.00233955
91

In [ ]:
[x for x in testdf.columns if x not in train_X.columns]

['target']

#Xgboost Modelling

In [ ]:
predictions=np.zeros(len(testdf))

for i,(train_index, val_index) in enumerate(kfold.split(X,Y)):
    train_X, val_X = X.iloc[train_index,:], X.iloc[val_index,:]
    train_Y, val_Y = Y.iloc[train_index], Y.iloc[val_index]

    print("The score for fold number {:03d}".format(i))
    # params configuration
    params = { 
   "objective": "binary:logistic",
   "booster": "gbtree",
   "eval_metric": "auc",
   "eta": 0.1, 
   "min_child_weight": 100,
   #"subsample": 0.85,
   #"colsample_bytree": 0.85,
   #"max_depth": 7,
   #"lambda":0.2,
   #"alpha":0.5,
   "scale_pos_weight":0.7
}

    d_train = xgb.DMatrix(train_X, train_Y)
    d_valid = xgb.DMatrix(val_X, val_Y)
    d_test = xgb.DMatrix(testdf)
    
    watchlist = [(d_train, 'train'), (d_valid, 'valid')]
    model = xgb.train(params, d_train, 5000,  watchlist,  maximize=True, verbose_eval=50, early_stopping_rounds=5)
                        
    preds = model.predict(d_test,ntree_limit=model.best_ntree_limit)
    predictions+=preds

The score for fold number 000
[0]	train-auc:0.808459	valid-auc:0.807304
Multiple eval metrics have been passed: 'valid-auc' will be used for early stopping.

Will train until valid-auc hasn't improved in 5 rounds.
[50]	train-auc:0.842105	valid-auc:0.837291
Stopping. Best iteration:
[57]	train-auc:0.84285	valid-auc:0.837811

The score for fold number 001
[0]	train-auc:0.813615	valid-auc:0.809265
Multiple eval metrics have been passed: 'valid-auc' will be used for early stopping.

Will train until valid-auc hasn't improved in 5 rounds.
[50]	train-auc:0.842117	valid-auc:0.834036
Stopping. Best iteration:
[93]	train-auc:0.847849	valid-auc:0.838078

The score for fold number 002
[0]	train-auc:0.81014	valid-auc:0.797245
Multiple eval metrics have been passed: 'valid-auc' will be used for early stopping.

Will train until valid-auc hasn't improved in 5 rounds.
[50]	train-auc:0.843795	valid-auc:0.831498
Stopping. Best iteration:
[59]	train-auc:0.844915	valid-auc:0.831878

The score for fold number 003
[0]	train-auc:0.813736	valid-auc:0.798733
Multiple eval metrics have been passed: 'valid-auc' will be used for early stopping.

Will train until valid-auc hasn't improved in 5 rounds.
Stopping. Best iteration:
[42]	train-auc:0.842603	valid-auc:0.826626

In [ ]:
feat_df=pd.DataFrame(model.get_fscore().items(), columns=['feature','importance']).sort_values('importance', ascending=False)
feat_df

                     feature  importance
1                      var15         208
2                      var38         164
0                saldo_var30          93
5     saldo_medio_var5_hace2          47
4      saldo_medio_var5_ult1          32
10    saldo_medio_var5_hace3          31
17            num_var22_ult3          14
7   num_meses_var39_vig_ult3          12
18     saldo_medio_var5_ult3          12
11           num_var22_hace2          11
20                saldo_var5          11
3            num_var45_hace2          11
8                ind_var41_0          10
6    imp_op_var39_efect_ult1          10
19         imp_op_var41_ult1          10
12         imp_op_var39_ult1           9
14           num_var45_hace3           9
25            num_var45_ult3           8
15                     var36           6
26       num_meses_var5_ult3           5
22            num_var22_ult1           4
29                  num_var4           3
16   num_op_var41_efect_ult1           2
13   imp_op_var41_efect_ult3           2
21               saldo_var42           2
23        num_med_var45_ult3           2
24            num_var45_ult1           2
9    imp_op_var41_efect_ult1           1
27               num_var30_0           1
28   imp_op_var39_efect_ult3           1
30         num_op_var41_ult1           1

In [ ]:
traindf[feat_df.feature[0:10]]

       var15          var38  ...  saldo_medio_var5_ult3  num_var22_hace2
0         23   39205.170000  ...                   0.00                0
1         34   49278.030000  ...                   0.00                0
2         23   67333.770000  ...                   2.07                0
3         37   64007.970000  ...                 138.84                3
4         39  117310.979016  ...               13501.47                3
...      ...            ...  ...                    ...              ...
76015     48   60926.490000  ...                   0.00                0
76016     39  118634.520000  ...                   0.00               24
76017     23   74028.150000  ...                   3.00                0
76018     25   84278.160000  ...                   2.58                0
76019     46  117310.979016  ...                   0.00                0

[76020 rows x 10 columns]

# Modelling with selected features

In [1]:


X = traindf[feat_df.feature[0:5]]
Y = traindf['TARGET']


testIDs=testdf.ID
testdf=testdf[feat_df.feature[0:5]]

In [ ]:
predictions=np.zeros(len(testdf))

for i,(train_index, val_index) in enumerate(kfold.split(X,Y)):
    train_X, val_X = X.iloc[train_index,:], X.iloc[val_index,:]
    train_Y, val_Y = Y.iloc[train_index], Y.iloc[val_index]

    print("The score for fold number {:03d}".format(i))
    # params configuration
    params = { 
   "objective": "binary:logistic",
   "booster": "gbtree",
   "eval_metric": "auc",
   "eta": 0.1, 
   "min_child_weight": 120,
   "subsample": 0.8,
   "colsample_bytree": 0.8,
   "max_depth": 6,
   #"lambda":0.10,
   #"alpha":0.5
   
              }

    d_train = xgb.DMatrix(train_X, train_Y)
    d_valid = xgb.DMatrix(val_X, val_Y)
    d_test = xgb.DMatrix(testdf)
    
    watchlist = [(d_train, 'train'), (d_valid, 'valid')]
    model = xgb.train(params, d_train, 5000,  watchlist,  maximize=True, verbose_eval=50, early_stopping_rounds=5)
                        
    preds = model.predict(d_test,ntree_limit=model.best_ntree_limit)
    predictions+=preds

In [ ]:
predictions=predictions/4

In [ ]:
submission=testdf
submission["ID"]=testIDs

In [ ]:
submission["TARGET"]=predictions

In [ ]:
submission=submission[["ID","TARGET"]]
submission.head()

       ID    TARGET
76020   2  0.046293
76021   5  0.057498
76022   6  0.009051
76023   7  0.019020
76024   9  0.009098

In [ ]:
from google.colab import files

submission.to_csv('submission_df.csv',index=False)
files.download('submission_df.csv')